services:
  backend:  # FastAPI
    build:
      context: ./Back
    ports:
      - "8000:8000"
    env_file:
      - ./Back/.env
    depends_on:
      - frontend

  frontend:  # React
    build:
      context: ./Front
    ports:
      - "80:5173"
