"""앨범용 db

Revision ID: d5a2822174e0
Revises: c2ddc27f40ac
Create Date: 2025-07-10 15:27:07.130455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a2822174e0'
down_revision: Union[str, None] = 'c2ddc27f40ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_songs', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('playlist_songs', sa.Column('position', sa.Integer(), nullable=False))
    op.add_column('playlist_songs', sa.Column('album_group_id', sa.String(length=255), nullable=True))
    op.add_column('playlist_songs', sa.Column('album_group_name', sa.String(length=255), nullable=True))
    op.add_column('playlist_songs', sa.Column('is_album_group', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_playlist_songs_album_group_id'), 'playlist_songs', ['album_group_id'], unique=False)
    op.create_index(op.f('ix_playlist_songs_id'), 'playlist_songs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_playlist_songs_id'), table_name='playlist_songs')
    op.drop_index(op.f('ix_playlist_songs_album_group_id'), table_name='playlist_songs')
    op.drop_column('playlist_songs', 'is_album_group')
    op.drop_column('playlist_songs', 'album_group_name')
    op.drop_column('playlist_songs', 'album_group_id')
    op.drop_column('playlist_songs', 'position')
    op.drop_column('playlist_songs', 'id')
    # ### end Alembic commands ###
